### ISSUE TITLE
Notification Required a Descriptor for the characteristic  

### ISSUE THREAD

**Issue by pollux-** [devunwired/accessory-samples#4]
Without having a Descriptor, How the Notification will work ??

We had built a peripheral  in iOS which simulate functionality of a LOCK , Reading and writing the characteristic  working perfectly fine. But we are failing to get the notification when I connect to the peripheral using android as central. After Reading the doc, I could able to figure out issue was, we didn't had a descriptor for characteristic.  How the iOS central receiving the notification ??? If descriptor filed was missing ???

But when I had checked this source, you are not creating any descriptor for the characteristic, still I'm getting notification.  How this is possible ??

As per the Android doc, we have to do this to enable Notification.

_mBluetoothGatt.setCharacteristicNotification(characteristic, enabled);
...
BluetoothGattDescriptor descriptor = characteristic.getDescriptor(
        UUID.fromString(SampleGattAttributes.CLIENT_CHARACTERISTIC_CONFIG));
descriptor.setValue(BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE);
mBluetoothGatt.writeDescriptor(descriptor);_

Please share your thoughts on this ?

Thanks !!

**Comment by devunwired** [comment]
A _Client Characteristic Configuration Descriptor_ is a [standard descriptor definition](https://developer.bluetooth.org/gatt/descriptors/Pages/DescriptorViewer.aspx?u=org.bluetooth.descriptor.gatt.client_characteristic_configuration.xml) required by some adopted profiles, but it is not required for communication to take place.

The descriptor simply facilitates a standard method for allowing clients to signal a server that they are interested in notifications. The GATT server can also use those signals to be smarter about when to enable/disable triggering any notifications at all…and to whom they should be delivered. Some implementations simply use a property on the characteristic that needs to be set (rather than a full descriptor).

This example skips over all of that, and simply delivers notifications all the time to any connected device (whether it asked for notifications or not). How your particular peripheral device monitors when to trigger is up to you. The only requirement of the Android central is to call `setCharacteristicNotification()` to allow its `onCharacteristicChanged()` callback to trigger when those events are received by the device.

**Comment by bennetlee** [comment]
Hi pollux, devunwired:

which code are you referring to that didn't need descriptor to trigger onCharacteristicChanged()? I am encountering similar issues where the characteristic I am using does not have a descriptor, and I am not able to trigger onCharacteristicChanged() even though I had call setCharacteristicNotification() in my code. Kindly advise. Thanks!
